server:
  port: 8989
spring:
  application:
    name: default-eureka-provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://49.4.95.115:8761/eureka/
    fetch-registry: false
  instance:
    prefer-ip-address: true
