server:
  port: 8777
spring:
  application:
    name: consumer-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://114.116.53.146:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
