server:
  port: 8777
spring:
  application:
    name: consumer-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://49.4.95.115:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
